### ISSUE TITLE
How to run Metaworld?

### ISSUE THREAD

**Issue by dyth** [tseyde/decqn#1]

**Comment by tseyde** [comment]
For setting up Meta-World, please follow the installation instructions on their GitHub page. We have added a Meta-World wrapper to the new branch ```feature/metaworld-wrapper```. After successful installation, their environments can then be run with the ```metaworld_``` prefix, e.g. ```metaworld_pick-place-v2```.

**Comment by dyth** [comment]
Many thanks, @tseyde for the fast reply!
