### ISSUE TITLE
the illustrative examples

### ISSUE THREAD

**Issue by KornbergFresnel** [tseyde/decqn#2]
Hi, the authors,

I have some doubts about the description of matrix games in your paper, and I didn’t find any details about them, e.g., the dynamic/states of climbing game. Could you give the implementation of these environments in this repo? or answer it in this thread. Thanks a lot.

**Comment by tseyde** [comment]
Hi Ming, thanks so much for your interest! 
For the matrix game variations that leverage pointmass dynamics we used the DeepMind Control Suite pointmass task with a custom reward wrapper. Matrix game actions serve as discrete acceleration inputs to the DMC task, and rewards are computed directly based on the input actions (e.g. Penalty game) or resulting pointmass state (e.g. Climbing game with state reward variation). Hope that helps 🙂
